export const RealisationList = [
	{
		title: "Espace Gambon",
		icon: "fab fa-wordpress icon-realisation mx-2",
		iconF: "fab fa-php icon-realisation mx-2",
		source: "./images/espace.png",
		link: "https://espace-gambon.fr/",
	},
	{
		title: "Disability Provider",
		icon: "fab fa-wordpress icon-realisation mx-2",
		iconF: "fab fa-php icon-realisation mx-2",
		source: "./images/disabilityprovider.png",
		link: "https://mydisabilityprovider.com.au/",
	},

	{
		title: "Search Movie App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		source: "./images/movie-search.png",
		link: "https://movieapp-99013.web.app/",
		github: "https://github.com/TiemaCoulibaly/react_search-movie",
	},
	{
		title: "Pomodoro App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		link: "https://pomodoro-feca0.web.app/",
		source: "./images/pomodoroApp.png",
		github: "https://github.com/TiemaCoulibaly/pomodoro",
	},
	{
		title: "Cryptocurrency App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		iconL: "fab fa-node icon-realisation mx-2",
		link: "https://crystal-crypto.herokuapp.com/",
		source: "./images/crystalfront2.png",
		github: "https://github.com/TiemaCoulibaly/Crypto-project",
	},
];
