export const RealisationList = [
	{
		title: "Espace Gambon",
		icon: "fab fa-wordpress icon-realisation mx-2",
		iconF: "fab fa-php icon-realisation mx-2",
		source: "./images/espace.png",
		link: "https://espace-gambon.fr/",
	},
	{
		title: "ToDo List",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		source: "./images/todo.png",
		link: "https://cryptic-cliffs-02336.herokuapp.com/",
	},
	{
		title: "Social CatchUp",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-js-square icon-realisation mx-2",
		source: "./images/social1.png",
		link: "http://makeitdigital.ml/",
	},
	{
		title: "Disability Provider",
		icon: "fab fa-wordpress icon-realisation mx-2",
		iconF: "fab fa-php icon-realisation mx-2",
		source: "./images/disabilityprovider.png",
		link: "https://mydisabilityprovider.com.au/",
	},
	{
		title: "Search Movie App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		source: "./images/movieApp.png",
		link: "https://movieapp-99013.web.app/",
	},
	{
		title: "Pomodoro App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		link: "https://pomodoro-feca0.web.app/",
		source: "./images/pomodoroApp.png",
	},
	{
		title: "Cryptocurrency App",
		icon: "fab fa-html5 icon-realisation mx-2",
		iconF: "fab fa-css3-alt icon-realisation mx-2",
		iconS: "fab fa-react icon-realisation mx-2",
		link: "https://github.com/TiemaCoulibaly/Crypto-project",
		source: "./images/crystal.png",
	},
];
